apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_55a2b7ca05f9
          imagePullPolicy: Always
          env:
            - name: VITE_KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: client-id
            - name: VITE_FRONT_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: front-redirect-uri
            - name: VITE_FRONT_KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: front-kakao-redirect-uri
            - name: VITE_BACK_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: back-redirect-uri
            - name: VITE_BACK_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: back-kakao-redirect-uri