apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  redirect-uri: aHR0cHM6Ly9rNTY3MzNiMzM1OTYyYS51c2VyLWFwcC5rcmFtcG9saW5lLmNvbQ==
  redirect-uri-back: aHR0cHM6Ly9rZmZhOTgyNGFmZmQ5YS51c2VyLWFwcC5rcmFtcG9saW5lLmNvbQ==
	client-id: YWFkOWZmZmFmZjViNjY1NWI5OTE0ODdjNWZmOGI0NDU=